version: "3.5"
services:

  trino-coordinator:
    image: trinodb/trino:latest
    container_name: trino-coordinator
    hostname: trino
    ports:
      - "8443:8080"
      - "8080:8080"
    environment:
      - TRINO_PORT
      - TRINO_SHARED_SECRET
      - TRINO_ORCHESTRATOR_NODE_ID
      - TRINO_IS_COORDINATOR
      - TRINO_INCLUDE_COORDINATOR=false
      - TRINO_COORDINATOR_URL
      - TRINO_LOG_TRINO_CLASS
      - TRINO_LOG_COM_CLASS
      - TRINO_LOG_FR_CLASS
      - TRINO_KEYSTORE_PATH
      - TRINO_KEYSTORE_KEY
      - TRINO_ENV
    volumes:
      - ./trino/config/:/etc/trino/
      - ./trino/ssl:/etc/trino/ssl
      - trino-data-node-coordinator:/data/trino
    logging:
      options:
        max-size: 10m
        max-file: "3"

  trino-worker:
    image: trinodb/trino
    container_name: trino-worker1
    hostname: worker-1
    environment:
      - TRINO_PORT=9090
      - TRINO_SHARED_SECRET
      - TRINO_ORCHESTRATOR_NODE_ID=30dc1c84-a322-48d1-b92f-65c4fd037bc0
      - TRINO_IS_COORDINATOR=false
      - TRINO_INCLUDE_COORDINATOR=false
      - TRINO_COORDINATOR_URL=https://trino-coordinator:8080
      - TRINO_LOG_TRINO_CLASS
      - TRINO_LOG_COM_CLASS
      - TRINO_LOG_FR_CLASS
      - TRINO_KEYSTORE_PATH
      - TRINO_KEYSTORE_KEY
      - TRINO_ENV
    volumes:
      - ./trino/config/:/etc/trino/
      - ./trino/ssl:/etc/trino/ssl
      - trino-data-node-worker-1:/data/trino
    logging:
      options:
        max-size: 10m
        max-file: "3"

  trino-worker-2:
    image: trinodb/trino
    container_name: trino-worker-2
    hostname: worker2
    ports:
      - "8082:8080"
    environment:
      - TRINO_PORT=9091
      - TRINO_SHARED_SECRET
      - TRINO_ORCHESTRATOR_NODE_ID=def9a816-a68b-4e07-a799-8e8df7eec15a
      - TRINO_IS_COORDINATOR=false
      - TRINO_INCLUDE_COORDINATOR=false
      - TRINO_COORDINATOR_URL=https://trino:8080
      - TRINO_LOG_TRINO_CLASS
      - TRINO_LOG_COM_CLASS
      - TRINO_LOG_FR_CLASS
      - TRINO_KEYSTORE_PATH
      - TRINO_KEYSTORE_KEY
      - TRINO_ENV
    volumes:
      - ./trino/config/:/etc/trino/
      - ./trino/ssl:/etc/trino/ssl
      - trino-data-node-worker-2:/data/trino
    logging:
      options:
        max-size: 10m
        max-file: "3"

  minio:
    image: minio/minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/docker-entrypoint.sh minio server /data --console-address :9001
      "
    volumes:
      - minio_storage:/data
    environment:
        - MINIO_ROOT_USER
        - MINIO_ROOT_PASSWORD
    ports:
      - "9001:9001"
  createbuckets:
    image: minio/mc
    network_mode: host
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add mys3 http://localhost:9000 $ACCES_KEY $ACCES_KEY_SECRET;
      /usr/bin/mc mb example;
      /usr/bin/mc policy set public example;
      exit 0;
      "
volumes:
  trino-data-node-coordinator:
  trino-data-node-worker-1:
  trino-data-node-worker-2:
  minio_storage: 
